const translations = {
    EN: {
        'zaloguj się': 'Log in', 
        'nazwa użytkownika': 'Username',
        'hasło': 'Password',
        'zarejestruj się': 'Register',
        'odzyskaj hasło': 'Retrive password',
        'strona główna': 'Home',
        'trendujące': 'Trending',
        'wykresy': 'Charts',
        'porównania': 'Comparison',
        'wyloguj się': 'Log out',
        'witaj': 'Welcome',
        'analizy wykresów kryptowalut': 'Stock analysis news',
        'kliknij po więcej': 'Click for more',
        'status konta': 'Account status',
        'wartość netto': 'Net worth',
        'pozostałe fundusze': 'Spare money',
        'nowości o spadku bitcoina': 'Bitcoin crash news',
        'nowe nadchodzące kryptowaluty': 'New groundbreaking crypto incomming',
        'oczekiwanie na dane': 'Waiting for data',
        'cena': 'Price',
        'wpisz nazwę kryptowaluty': 'Enter crypto name',
        'wpisz nazwę pierwszej kryptowaluty': 'Enter first crypto name',
        'wpisz nazwę drugiej kryptowaluty': 'Enter second crypto name',
        'porównaj': 'Compare',
        'wyszukaj pierwszego coina': 'Search for the first coin',
        'wyszukaj drugiego coina': 'Search for the second coin',
        'aktualna cena': 'Current price',
        'przekroczono limit wywołań API. Proszę zaczekać i spróbować ponownie później': 'API Calls limit exceeded, please wait and try again later',
        'zamknij': 'Close',
        'dane profilowe': 'Profile info',
        'modyfikuj profil': 'Modify profile',
        'bezpieczeństwo': 'Security',
        'twoje hasło jest zabezpieczone': 'Your password is encrypted',
        'na zawsze': 'Forever',
        'zmień hasło': 'Change password',
        'ustawienia aplikacji': 'App settings',
        'język': 'Language',
        'tryb koloru': 'Color mode',
        'zapisz': 'Save',
        'akcje': 'Actions',
        'konto': 'Account',
        'aktywne': 'active',
        'wyłączone': 'disabled',
        'wyłącz konto': 'Disable account',
        'usuń konto': 'Delete account',
        'jasny': 'Light',
        'ciemny': 'Dark',
        'modyfikuj dane użytkownika': 'Modify user data',
        'modyfikuj lekkie dane': 'Modify light data',
        'dodaj nowe profilowe': 'Upload new profile image',
        'dodaj profilowe': 'Upload profile picture',
        'nie wybrano pliku': 'No file selected',
        'zastosuj': 'Apply',
        'powtórz hasło': 'Repeat password'
    },
}

const translate = (language, key) => {
    return  translations[language] && translations[language][key.toLowerCase()] ? translations[language][key.toLowerCase()] : key;
}

export default translate;